---
title: "Nuclear-norm multivariate response regression simulation log"
output:
  pdf_document: default
  html_document:
    df_print: paged
---
## October 27, 2018 
All files zipped and saved as 27Oct2018. This simulationw as comparing our method to lasso and sqrt-root lasso methods in terms of model error, prediction error, Malanobis distance, and TPR/FPR. We tried both a Normal data generating model and a T5 data generating model. 
```{r, echo=FALSE, eval= FALSE, cache=TRUE}
# ---- Write and compress results 
setwd("/Volumes/homes/NN_MVR/Normal_AR1_Results/")
rho <- c(0, 0.5, 0.7, 0.9, 0.95)
Norm.Results <- NULL
for(j in 1:100){
  temp <- readRDS(paste("Normal_AR1_0_", j, ".RDS", sep=""))
  Norm.Results <- rbind(Norm.Results, temp)
}
for(j in 1:100){
  temp <- readRDS(paste("Normal_AR1_5_", j, ".RDS", sep=""))
  Norm.Results <- rbind(Norm.Results, temp)
}
for(j in 1:100){
  temp <- readRDS(paste("Normal_AR1_7_", j, ".RDS", sep=""))
  Norm.Results <- rbind(Norm.Results, temp)
}
for(j in 1:100){
  temp <- readRDS(paste("Normal_AR1_9_", j, ".RDS", sep=""))
  Norm.Results <- rbind(Norm.Results, temp)
}
for(j in 1:100){
  temp <- readRDS(paste("Normal_AR1_95_", j, ".RDS", sep=""))
  Norm.Results <- rbind(Norm.Results, temp)
}

saveRDS(Norm.Results, "Normal_AR1_Results_6Nov2018.RDS")


# --------
setwd("/Volumes/homes/NN_MVR/Normal_Const_Results/")
rho <- c(0, 0.3, 0.5, 0.7, 0.9)
Norm.Results <- NULL
for(j in 1:100){
  temp <- readRDS(paste("Normal_Const_0_", j, ".RDS", sep=""))
  Norm.Results <- rbind(Norm.Results, temp)
}
for(j in c((1:100)[-80], 1)){
  temp <- readRDS(paste("Normal_Const_3_", j, ".RDS", sep=""))
  Norm.Results <- rbind(Norm.Results, temp)
}
for(j in 1:100){
  temp <- readRDS(paste("Normal_Const_5_", j, ".RDS", sep=""))
  Norm.Results <- rbind(Norm.Results, temp)
}
for(j in 1:100){
  temp <- readRDS(paste("Normal_Const_7_", j, ".RDS", sep=""))
  Norm.Results <- rbind(Norm.Results, temp)
}
for(j in 1:100){
  temp <- readRDS(paste("Normal_Const_9_", j, ".RDS", sep=""))
  Norm.Results <- rbind(Norm.Results, temp)
}

saveRDS(Norm.Results, "Normal_Const_Results_6Nov2018.RDS")




# ---- Write and compress results 
setwd("/Volumes/homes/NN_MVR/NormalHet_AR1_Results/")
rho <- c(0, 0.5, 0.7, 0.9, 0.95)
Norm.Results <- NULL
for(j in 1:100){
  temp <- readRDS(paste("NormalHet_AR1_0_", j, ".RDS", sep=""))
  Norm.Results <- rbind(Norm.Results, temp)
}
for(j in 1:100){
  temp <- readRDS(paste("NormalHet_AR1_5_", j, ".RDS", sep=""))
  Norm.Results <- rbind(Norm.Results, temp)
}
for(j in 1:100){
  temp <- readRDS(paste("NormalHet_AR1_7_", j, ".RDS", sep=""))
  Norm.Results <- rbind(Norm.Results, temp)
}
for(j in 1:100){
  temp <- readRDS(paste("NormalHet_AR1_9_", j, ".RDS", sep=""))
  Norm.Results <- rbind(Norm.Results, temp)
}
for(j in 1:100){
  temp <- readRDS(paste("NormalHet_AR1_95_", j, ".RDS", sep=""))
  Norm.Results <- rbind(Norm.Results, temp)
}

saveRDS(Norm.Results, "NormalHet_AR1_Results_6Nov2018.RDS")


# --------
setwd("/Volumes/homes/NN_MVR/NormalHet_Const_Results/")
rho <- c(0, 0.3, 0.5, 0.7, 0.9)
Norm.Results <- NULL
for(j in 1:100){
  temp <- readRDS(paste("NormalHet_Const_0_", j, ".RDS", sep=""))
  Norm.Results <- rbind(Norm.Results, temp)
}
for(j in 1:100){
  temp <- readRDS(paste("NormalHet_Const_3_", j, ".RDS", sep=""))
  Norm.Results <- rbind(Norm.Results, temp)
}
for(j in 1:100){
  temp <- readRDS(paste("NormalHet_Const_5_", j, ".RDS", sep=""))
  Norm.Results <- rbind(Norm.Results, temp)
}
for(j in 1:100){
  temp <- readRDS(paste("NormalHet_Const_7_", j, ".RDS", sep=""))
  Norm.Results <- rbind(Norm.Results, temp)
}
for(j in 1:100){
  temp <- readRDS(paste("NormalHet_Const_9_", j, ".RDS", sep=""))
  Norm.Results <- rbind(Norm.Results, temp)
}

saveRDS(Norm.Results, "NormalHet_Const_Results_6Nov2018.RDS")



```


```{r, fig.show='hold', echo=FALSE, fig.align='center', out.width='.49\\linewidth', cache=TRUE}
setwd("/Volumes/homes/NN_MVR/Normal_AR1_Results/")
temp <- readRDS("Normal_AR1_Results_6Nov2018.RDS")
Norm.Results <- temp
rho <- c(0, 0.5, 0.7, 0.9, 0.95)

# --- melt data frames to display results more easily -- 
ModelErrDat <- data.frame("NN MVR" = unlist(Norm.Results[,1]), "Lasso-1" = unlist(Norm.Results[,6]), "Lasso-q" = unlist(Norm.Results[,11]), "Calibrated MVR" = unlist(Norm.Results[,21]), "MRCE-opt" = unlist(Norm.Results[,26]),
"MRCE-ap" = unlist(Norm.Results[,31]), "rho" = rep(rho, each=100))
library(reshape)

ModelErrDat <- melt(ModelErrDat, id=c("rho"))
ModelErrDat$variable <- factor(ModelErrDat$variable,
    levels = levels(ModelErrDat$variable)[c(2,3,4,1,5,6)], ordered = TRUE)

names(ModelErrDat) <- c("rho", "Method", "value")
ModelErrDat$Method <- gsub(".", "-", ModelErrDat$Method, fixed = TRUE)

library(ggplot2)
setwd("/Users/aaronmolstad/Dropbox/NN_MRR/Manuscript/Plots")
pdf("Normal_AR1_ME.pdf", width=2.75, height=2.25)
ggplot(ModelErrDat, aes(y=value, x= as.factor(rho), fill = Method)) + geom_boxplot(outlier.size = 0.1) +   ylab("Model Error") + xlab(expression(rho)) +  theme_classic() + scale_fill_grey(start = 0, end = .99) + ylim(c(0, 10)) + guides(fill = FALSE)
dev.off()
# 
# temp <- aggregate(ModelErrDat$value, by=list(as.factor(ModelErrDat$rho), ModelErrDat$Method), function(x)mean(x, na.rm=TRUE))
# 
# colnames(temp) <- c("rho", "Method", "value")
# 
# library(ggplot2)
# ggplot(temp, aes(y=value, x= rho, group = Method, color = Method)) + geom_line() +   ylab("Model Error") + xlab(expression(rho)) +  theme_classic() + scale_fill_grey(start = 0, end = .99) + ylim(c(0, 10))
 

# --- melt data frames to display results more easily -- 
PredErrDat <- data.frame("NN MVR" = unlist(Norm.Results[,2]), "Lasso-1" = unlist(Norm.Results[,7]), "Lasso-q" = unlist(Norm.Results[,12]), "Calibrated MVR" = unlist(Norm.Results[,22]), "MRCE-Oracle" = unlist(Norm.Results[,27]),
"MRCE-Approx" = unlist(Norm.Results[,32]), "rho" = rep(rho, each=100))
library(reshape)

PredErrDat <- melt(PredErrDat, id=c("rho"))
PredErrDat$variable <- factor(PredErrDat$variable,
    levels = levels(PredErrDat$variable)[c(2,3,4,1,5,6)], ordered = TRUE)
names(PredErrDat) <- c("rho", "Method", "value")

PredErrDat$Method <- gsub(".", "-", PredErrDat$Method, fixed = TRUE)
library(ggplot2)
setwd("/Users/aaronmolstad/Dropbox/NN_MRR/Manuscript/Plots")
pdf("Normal_AR1_PE.pdf",width=4.5, height=2.25)
ggplot(PredErrDat, aes(y=value, x= as.factor(rho), fill = Method)) + geom_boxplot(outlier.size = 0.1) +   ylab("Prediction Error") + xlab(expression(rho)) +  theme_classic() + scale_fill_grey(start = 0, end = .99)
dev.off()

```




```{r, fig.show='hold', echo=FALSE, fig.align='center', out.width='.49\\linewidth', cache=TRUE}
setwd("/Volumes/homes/NN_MVR/Normal_Const_Results/")
temp <- readRDS("Normal_Const_Results_6Nov2018.RDS")
Norm.Results <- temp
rho <- c(0, 0.3, 0.5, 0.7, 0.9)

# --- melt data frames to display results more easily -- 
ModelErrDat <- data.frame("NN MVR" = unlist(Norm.Results[,1]), "Lasso-1" = unlist(Norm.Results[,6]), "Lasso-q" = unlist(Norm.Results[,11]), "Calibrated MVR" = unlist(Norm.Results[,21]), "MRCE-opt" = unlist(Norm.Results[,26]),
"MRCE-ap" = unlist(Norm.Results[,31]), "rho" = rep(rho, each=100))
library(reshape)

ModelErrDat <- melt(ModelErrDat, id=c("rho"))
ModelErrDat$variable <- factor(ModelErrDat$variable,
    levels = levels(ModelErrDat$variable)[c(2,3,4,1,5,6)], ordered = TRUE)

names(ModelErrDat) <- c("rho", "Method", "value")
ModelErrDat$Method <- gsub(".", "-", ModelErrDat$Method, fixed = TRUE)

library(ggplot2)
setwd("/Users/aaronmolstad/Dropbox/NN_MRR/Manuscript/Plots")
pdf("Normal_Const_ME.pdf",  width=2.75, height=2.25)
ggplot(ModelErrDat, aes(y=value, x= as.factor(rho), fill = Method)) + geom_boxplot(outlier.size = 0.1) +   ylab("Model Error") + xlab(expression(rho)) +  theme_classic() + scale_fill_grey(start = 0, end = .99)  + guides(fill = FALSE)
dev.off()
# 
# temp <- aggregate(ModelErrDat$value, by=list(as.factor(ModelErrDat$rho), ModelErrDat$Method), function(x)mean(x, na.rm=TRUE))
# 
# colnames(temp) <- c("rho", "Method", "value")
# 
# library(ggplot2)
# ggplot(temp, aes(y=value, x= rho, group = Method, color = Method)) + geom_line() +   ylab("Model Error") + xlab(expression(rho)) +  theme_classic() + scale_fill_grey(start = 0, end = .99) + ylim(c(0, 10))
 

# --- melt data frames to display results more easily -- 
PredErrDat <- data.frame("NN MVR" = unlist(Norm.Results[,2]), "Lasso-1" = unlist(Norm.Results[,7]), "Lasso-q" = unlist(Norm.Results[,12]), "Calibrated MVR" = unlist(Norm.Results[,22]), "MRCE-Oracle" = unlist(Norm.Results[,27]),
"MRCE-Approx" = unlist(Norm.Results[,32]), "rho" = rep(rho, each=100))
library(reshape)

PredErrDat <- melt(PredErrDat, id=c("rho"))
PredErrDat$variable <- factor(PredErrDat$variable,
    levels = levels(PredErrDat$variable)[c(2,3,4,1,5,6)], ordered = TRUE)
names(PredErrDat) <- c("rho", "Method", "value")

PredErrDat$Method <- gsub(".", "-", PredErrDat$Method, fixed = TRUE)
library(ggplot2)
setwd("/Users/aaronmolstad/Dropbox/NN_MRR/Manuscript/Plots")
pdf("Normal_Const_PE.pdf",width=4.5, height=2.25)
ggplot(PredErrDat, aes(y=value, x= as.factor(rho), fill = Method)) + geom_boxplot(outlier.size = 0.1) +   ylab("Prediction Error") + xlab(expression(rho)) +  theme_classic() + scale_fill_grey(start = 0, end = .99)
dev.off()

```





```{r, fig.show='hold', echo=FALSE, fig.align='center', out.width='.49\\linewidth', cache=TRUE}
setwd("/Volumes/homes/NN_MVR/NormalHet_Const_Results/")
temp <- readRDS("NormalHet_Const_Results_6Nov2018.RDS")
Norm.Results <- temp
rho <- c(0, 0.3, 0.5, 0.7, 0.9)

# --- melt data frames to display results more easily -- 
ModelErrDat <- data.frame("NN MVR" = unlist(Norm.Results[,1]), "Lasso-1" = unlist(Norm.Results[,6]), "Lasso-q" = unlist(Norm.Results[,11]), "Calibrated MVR" = unlist(Norm.Results[,21]), "MRCE-opt" = unlist(Norm.Results[,26]),
"MRCE-ap" = unlist(Norm.Results[,31]), "rho" = rep(rho, each=100))
library(reshape)

ModelErrDat <- melt(ModelErrDat, id=c("rho"))
ModelErrDat$variable <- factor(ModelErrDat$variable,
    levels = levels(ModelErrDat$variable)[c(2,3,4,1,5,6)], ordered = TRUE)

names(ModelErrDat) <- c("rho", "Method", "value")
ModelErrDat$Method <- gsub(".", "-", ModelErrDat$Method, fixed = TRUE)

library(ggplot2)
setwd("/Users/aaronmolstad/Dropbox/NN_MRR/Manuscript/Plots")
pdf("NormalHet_Const_ME.pdf", width=2.75, height=2.25)
ggplot(ModelErrDat, aes(y=value, x= as.factor(rho), fill = Method)) + geom_boxplot(outlier.size = 0.1) +   ylab("Model Error") + xlab(expression(rho)) +  theme_classic() + scale_fill_grey(start = 0, end = .99)  + guides(fill = FALSE)
dev.off()
# 
# temp <- aggregate(ModelErrDat$value, by=list(as.factor(ModelErrDat$rho), ModelErrDat$Method), function(x)mean(x, na.rm=TRUE))
# 
# colnames(temp) <- c("rho", "Method", "value")
# 
# library(ggplot2)
# ggplot(temp, aes(y=value, x= rho, group = Method, color = Method)) + geom_line() +   ylab("Model Error") + xlab(expression(rho)) +  theme_classic() + scale_fill_grey(start = 0, end = .99) + ylim(c(0, 10))
 

# --- melt data frames to display results more easily -- 
PredErrDat <- data.frame("NN MVR" = unlist(Norm.Results[,2]), "Lasso-1" = unlist(Norm.Results[,7]), "Lasso-q" = unlist(Norm.Results[,12]), "Calibrated MVR" = unlist(Norm.Results[,22]), "MRCE-Oracle" = unlist(Norm.Results[,27]),
"MRCE-Approx" = unlist(Norm.Results[,32]), "rho" = rep(rho, each=100))
library(reshape)

PredErrDat <- melt(PredErrDat, id=c("rho"))
PredErrDat$variable <- factor(PredErrDat$variable,
    levels = levels(PredErrDat$variable)[c(2,3,4,1,5,6)], ordered = TRUE)
names(PredErrDat) <- c("rho", "Method", "value")

PredErrDat$Method <- gsub(".", "-", PredErrDat$Method, fixed = TRUE)
library(ggplot2)
setwd("/Users/aaronmolstad/Dropbox/NN_MRR/Manuscript/Plots")
pdf("NormalHet_Const_PE.pdf", width=4.5, height=2.25)
ggplot(PredErrDat, aes(y=value, x= as.factor(rho), fill = Method)) + geom_boxplot(outlier.size = 0.1) +   ylab("Prediction Error") + xlab(expression(rho)) +  theme_classic() + scale_fill_grey(start = 0, end = .99)
dev.off()

```


```{r, fig.show='hold', echo=FALSE, fig.align='center', out.width='.49\\linewidth', cache=TRUE}
setwd("/Volumes/homes/NN_MVR/NormalHet_AR1_Results/")
temp <- readRDS("NormalHet_AR1_Results_6Nov2018.RDS")
Norm.Results <- temp
rho <- c(0, 0.5, 0.7, 0.9, 0.95)

# --- melt data frames to display results more easily -- 
ModelErrDat <- data.frame("NN MVR" = unlist(Norm.Results[,1]), "Lasso-1" = unlist(Norm.Results[,6]), "Lasso-q" = unlist(Norm.Results[,11]), "Calibrated MVR" = unlist(Norm.Results[,21]), "MRCE-opt" = unlist(Norm.Results[,26]),
"MRCE-ap" = unlist(Norm.Results[,31]), "rho" = rep(rho, each=100))
library(reshape)

ModelErrDat <- melt(ModelErrDat, id=c("rho"))
ModelErrDat$variable <- factor(ModelErrDat$variable,
    levels = levels(ModelErrDat$variable)[c(2,3,4,1,5,6)], ordered = TRUE)

names(ModelErrDat) <- c("rho", "Method", "value")
ModelErrDat$Method <- gsub(".", "-", ModelErrDat$Method, fixed = TRUE)

library(ggplot2)
setwd("/Users/aaronmolstad/Dropbox/NN_MRR/Manuscript/Plots")
pdf("NormalHet_AR1_ME.pdf",  width=2.75, height=2.25)
ggplot(ModelErrDat, aes(y=value, x= as.factor(rho), fill = Method)) + geom_boxplot(outlier.size = 0.1) +   ylab("Model Error") + xlab(expression(rho)) +  theme_classic() + scale_fill_grey(start = 0, end = .99)  + guides(fill = FALSE)
dev.off()
# 
# temp <- aggregate(ModelErrDat$value, by=list(as.factor(ModelErrDat$rho), ModelErrDat$Method), function(x)mean(x, na.rm=TRUE))
# 
# colnames(temp) <- c("rho", "Method", "value")
# 
# library(ggplot2)
# ggplot(temp, aes(y=value, x= rho, group = Method, color = Method)) + geom_line() +   ylab("Model Error") + xlab(expression(rho)) +  theme_classic() + scale_fill_grey(start = 0, end = .99) + ylim(c(0, 10))
 

# --- melt data frames to display results more easily -- 
PredErrDat <- data.frame("NN MVR" = unlist(Norm.Results[,2]), "Lasso-1" = unlist(Norm.Results[,7]), "Lasso-q" = unlist(Norm.Results[,12]), "Calibrated MVR" = unlist(Norm.Results[,22]), "MRCE-Oracle" = unlist(Norm.Results[,27]),
"MRCE-Approx" = unlist(Norm.Results[,32]), "rho" = rep(rho, each=100))
library(reshape)

PredErrDat <- melt(PredErrDat, id=c("rho"))
PredErrDat$variable <- factor(PredErrDat$variable,
    levels = levels(PredErrDat$variable)[c(2,3,4,1,5,6)], ordered = TRUE)
names(PredErrDat) <- c("rho", "Method", "value")

PredErrDat$Method <- gsub(".", "-", PredErrDat$Method, fixed = TRUE)
library(ggplot2)
setwd("/Users/aaronmolstad/Dropbox/NN_MRR/Manuscript/Plots")
pdf("NormalHet_AR1_PE.pdf", width=4.5, height=2.25)
ggplot(PredErrDat, aes(y=value, x= as.factor(rho), fill = Method)) + geom_boxplot(outlier.size = 0.1) +   ylab("Prediction Error") + xlab(expression(rho)) +  theme_classic() + scale_fill_grey(start = 0, end = .99)
dev.off()

```
